 <!-- Project Section -->
 
   <div class="w3-row-padding">

  <div class="w3-quarter w3-container">
 <h4 class="w3-border-bottom w3-border-light-grey w3-padding-16"  >สามเอ็ม คาร์แคร์ </h4>  
      <div class="w3-display-container">
ศูนย์บริการดูแลรักษารถยนต์ ด้วยผลิตภัณฑ์ 3M  
<p>
 <div > <a href="tel:0895294226">
           <div style="width:100%; background: #CCCCAA;text-align: center;padding: 8px; ">
                 <h3>โทร 089 529 4226</h3>
            </div>
         </a>  
</div> 
</p>      
    </div>

  </div>
  <div class="w3-quarter w3-container">
  <h4 class="w3-border-bottom w3-border-light-grey w3-padding-16"  >เวลาทำการ</h4>  
      <div class="w3-display-container">

      เปิดบริการทุกวัน  
        
       <p>
          <div >
  
  08:00–19:00&nbsp;&nbsp; วันอาทิตย์ 
</div>
<div>
  08:00–19:00&nbsp;&nbsp; วันจันทร์ 
   
</div>
<div>
 08:00–19:00&nbsp;&nbsp;  วันอังคาร 
  
</div>
<div>
  08:00–19:00&nbsp;&nbsp;  วันพุธ 
  
</div>
<div>
 08:00–19:00&nbsp;&nbsp; วันพฤหัสบดี 
   
</div>
<div>
  08:00–19:00&nbsp;&nbsp; วันศุกร์ 
  
</div>
<div>
  08:00–19:00&nbsp;&nbsp; วันเสาร์ 
</div>
</p>
 <br/> 

    </div>
  </div>


<!-- Facebook section -->
   <div class="w3-quarter w3-container">
      <h4 class="w3-border-bottom w3-border-light-grey w3-padding-16"  >ติดตามเรา</h4>  

      <div class="w3-display-container"  id="fb-root">
        <div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/th_TH/sdk.js#xfbml=1&version=v6.0&appId=218840994980078&autoLogAppEvents=1"></script>
<img src="img/webIcon/ffb.png">
        <div class="fb-like" data-href="https://www.facebook.com/tpc3mcarcare" data-width="" data-layout="button_count" data-action="like" data-size="large" data-share="true"></div>
<br/><br/>
         <script src="https://apis.google.com/js/platform.js"></script>

<div class="g-ytsubscribe" data-channelid="UCQ2WIjvqCYxN3s2Zg6Azn0w" data-layout="full" data-count="default"></div>

  </div>
<br/>
<a href="https://lin.ee/3FGRG2I"><img src="https://scdn.line-apps.com/n/line_add_friends/btn/th.png" alt="เพิ่มเพื่อน" height="36" border="0"></a>
  </div>
 

<!--END Facebook section -->

 
  <div class="w3-quarter w3-container">
  <h4 class="w3-border-bottom w3-border-light-grey w3-padding-16"  >สั่งซื้อสินค้า</h4>  
      <div class="w3-display-container" style="vertical-align: center;"> 
      <a href="https://www.lazada.co.th/shop/3m-carcare-the-pros-choice/" target="_blank">
 <img  src="img/webIcon/lazada.png" /> </a>
    </div>
  </div>

 </div>